/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreeRouteImport } from './routes/tree'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Weeks1RouteImport } from './routes/weeks/1'

const TreeRoute = TreeRouteImport.update({
  id: '/tree',
  path: '/tree',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Weeks1Route = Weeks1RouteImport.update({
  id: '/weeks/1',
  path: '/weeks/1',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tree': typeof TreeRoute
  '/weeks/1': typeof Weeks1Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tree': typeof TreeRoute
  '/weeks/1': typeof Weeks1Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tree': typeof TreeRoute
  '/weeks/1': typeof Weeks1Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tree' | '/weeks/1'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tree' | '/weeks/1'
  id: '__root__' | '/' | '/tree' | '/weeks/1'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TreeRoute: typeof TreeRoute
  Weeks1Route: typeof Weeks1Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tree': {
      id: '/tree'
      path: '/tree'
      fullPath: '/tree'
      preLoaderRoute: typeof TreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weeks/1': {
      id: '/weeks/1'
      path: '/weeks/1'
      fullPath: '/weeks/1'
      preLoaderRoute: typeof Weeks1RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TreeRoute: TreeRoute,
  Weeks1Route: Weeks1Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
