/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreeRouteImport } from './routes/tree'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Weeks9RouteImport } from './routes/weeks/9'
import { Route as Weeks6RouteImport } from './routes/weeks/6'
import { Route as Weeks4RouteImport } from './routes/weeks/4'
import { Route as Weeks2RouteImport } from './routes/weeks/2'
import { Route as Weeks12RouteImport } from './routes/weeks/12'
import { Route as Weeks11RouteImport } from './routes/weeks/11'
import { Route as Weeks1RouteImport } from './routes/weeks/1'

const TreeRoute = TreeRouteImport.update({
  id: '/tree',
  path: '/tree',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Weeks9Route = Weeks9RouteImport.update({
  id: '/weeks/9',
  path: '/weeks/9',
  getParentRoute: () => rootRouteImport,
} as any)
const Weeks6Route = Weeks6RouteImport.update({
  id: '/weeks/6',
  path: '/weeks/6',
  getParentRoute: () => rootRouteImport,
} as any)
const Weeks4Route = Weeks4RouteImport.update({
  id: '/weeks/4',
  path: '/weeks/4',
  getParentRoute: () => rootRouteImport,
} as any)
const Weeks2Route = Weeks2RouteImport.update({
  id: '/weeks/2',
  path: '/weeks/2',
  getParentRoute: () => rootRouteImport,
} as any)
const Weeks12Route = Weeks12RouteImport.update({
  id: '/weeks/12',
  path: '/weeks/12',
  getParentRoute: () => rootRouteImport,
} as any)
const Weeks11Route = Weeks11RouteImport.update({
  id: '/weeks/11',
  path: '/weeks/11',
  getParentRoute: () => rootRouteImport,
} as any)
const Weeks1Route = Weeks1RouteImport.update({
  id: '/weeks/1',
  path: '/weeks/1',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tree': typeof TreeRoute
  '/weeks/1': typeof Weeks1Route
  '/weeks/11': typeof Weeks11Route
  '/weeks/12': typeof Weeks12Route
  '/weeks/2': typeof Weeks2Route
  '/weeks/4': typeof Weeks4Route
  '/weeks/6': typeof Weeks6Route
  '/weeks/9': typeof Weeks9Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tree': typeof TreeRoute
  '/weeks/1': typeof Weeks1Route
  '/weeks/11': typeof Weeks11Route
  '/weeks/12': typeof Weeks12Route
  '/weeks/2': typeof Weeks2Route
  '/weeks/4': typeof Weeks4Route
  '/weeks/6': typeof Weeks6Route
  '/weeks/9': typeof Weeks9Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tree': typeof TreeRoute
  '/weeks/1': typeof Weeks1Route
  '/weeks/11': typeof Weeks11Route
  '/weeks/12': typeof Weeks12Route
  '/weeks/2': typeof Weeks2Route
  '/weeks/4': typeof Weeks4Route
  '/weeks/6': typeof Weeks6Route
  '/weeks/9': typeof Weeks9Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tree'
    | '/weeks/1'
    | '/weeks/11'
    | '/weeks/12'
    | '/weeks/2'
    | '/weeks/4'
    | '/weeks/6'
    | '/weeks/9'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tree'
    | '/weeks/1'
    | '/weeks/11'
    | '/weeks/12'
    | '/weeks/2'
    | '/weeks/4'
    | '/weeks/6'
    | '/weeks/9'
  id:
    | '__root__'
    | '/'
    | '/tree'
    | '/weeks/1'
    | '/weeks/11'
    | '/weeks/12'
    | '/weeks/2'
    | '/weeks/4'
    | '/weeks/6'
    | '/weeks/9'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TreeRoute: typeof TreeRoute
  Weeks1Route: typeof Weeks1Route
  Weeks11Route: typeof Weeks11Route
  Weeks12Route: typeof Weeks12Route
  Weeks2Route: typeof Weeks2Route
  Weeks4Route: typeof Weeks4Route
  Weeks6Route: typeof Weeks6Route
  Weeks9Route: typeof Weeks9Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tree': {
      id: '/tree'
      path: '/tree'
      fullPath: '/tree'
      preLoaderRoute: typeof TreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weeks/9': {
      id: '/weeks/9'
      path: '/weeks/9'
      fullPath: '/weeks/9'
      preLoaderRoute: typeof Weeks9RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weeks/6': {
      id: '/weeks/6'
      path: '/weeks/6'
      fullPath: '/weeks/6'
      preLoaderRoute: typeof Weeks6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weeks/4': {
      id: '/weeks/4'
      path: '/weeks/4'
      fullPath: '/weeks/4'
      preLoaderRoute: typeof Weeks4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weeks/2': {
      id: '/weeks/2'
      path: '/weeks/2'
      fullPath: '/weeks/2'
      preLoaderRoute: typeof Weeks2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weeks/12': {
      id: '/weeks/12'
      path: '/weeks/12'
      fullPath: '/weeks/12'
      preLoaderRoute: typeof Weeks12RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weeks/11': {
      id: '/weeks/11'
      path: '/weeks/11'
      fullPath: '/weeks/11'
      preLoaderRoute: typeof Weeks11RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weeks/1': {
      id: '/weeks/1'
      path: '/weeks/1'
      fullPath: '/weeks/1'
      preLoaderRoute: typeof Weeks1RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TreeRoute: TreeRoute,
  Weeks1Route: Weeks1Route,
  Weeks11Route: Weeks11Route,
  Weeks12Route: Weeks12Route,
  Weeks2Route: Weeks2Route,
  Weeks4Route: Weeks4Route,
  Weeks6Route: Weeks6Route,
  Weeks9Route: Weeks9Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
